name: Typhfun
author: GentlemanCheesy
description: A Slimefun4-Addon made from content on Typhon MC
version: '${project.version}'
website: https://github.com/GentlemanCheesy/Typhfun
main: net.typhonmc.typhfun.Typhfun
api-version: '1.20'
depend: [Slimefun]