name: Typhfun

author: GentlemanCheesy

description: A Slimefun4-Addon made from content on Typhon MC

main: me.gentlemancheesy.typhfun.TyphfunAddon

website: https://github.com/GentlemanCheesy/Typhfun

version: ${project.version}

api-version: 1.14

depend:
- Slimefun