name: Typhfun
authors: [Wheeler-Shigley,GentlemanCheesy]
description: A Slimefun4-Addon made from content on Typhon MC
version: '${project.version}'
website: https://github.com/GentlemanCheesy/Typhfun
main: net.typhonmc.typhfun.TyphfunPlugin
api-version: '1.20'
depend: [Slimefun]
commands:
  typhfun:
    description: Plugin root command
    usage: /<command> <argument>
    permission: typhfun.typhfun